export type TicketStatus = 'Open' | 'In Progress' | 'In Review' | 'Resolved' | 'Closed'
export type TicketPriority = 'Critical' | 'High' | 'Medium' | 'Low'
export type TicketQueue = 'Backend / API' | 'Frontend' | 'Infra / Cloud' | 'Data / DB' | 'Security' | 'Mobile'
export type Environment = 'Production' | 'Staging' | 'Development' | 'All environments'
export type Severity = 'P0 - Outage' | 'P1 - Degraded' | 'P2 - Minor' | 'P3 - Cosmetic'

export interface Comment {
  id: string
  author: string
  authorInitials: string
  avatarColor: string
  content: string
  timestamp: string
}

export interface Ticket {
  id: string
  title: string
  description: string
  status: TicketStatus
  priority: TicketPriority
  queue: TicketQueue
  assignee: string | null
  assigneeInitials: string | null
  avatarColor: string | null
  reporter: string
  environment: Environment
  createdAt: string
  updatedAt: string
  tags: string[]
  services: string[]
  severity: Severity
  comments: Comment[]
}

export const teamMembers = [
  { name: 'Rahul Kumar', initials: 'RK', color: 'bg-blue-500' },
  { name: 'Priya Sharma', initials: 'PS', color: 'bg-purple-500' },
  { name: 'Ankit Joshi', initials: 'AJ', color: 'bg-green-500' },
  { name: 'Sneha Mishra', initials: 'SM', color: 'bg-orange-500' },
  { name: 'Vivek Rao', initials: 'VR', color: 'bg-red-500' },
  { name: 'Arjun Mehta', initials: 'AM', color: 'bg-teal-500' },
]

export const initialTickets: Ticket[] = [
  {
    id: 'ENG-001',
    title: 'Allocation API returning 500 on concurrent requests',
    description: 'The /api/v2/allocations endpoint throws 500 Internal Server Error when 50+ concurrent requests are made. Issue began after deploying v3.4.2. Stack trace shows ORM connection pool exhausted (max: 10).',
    status: 'Open',
    priority: 'Critical',
    queue: 'Backend / API',
    assignee: 'Rahul Kumar',
    assigneeInitials: 'RK',
    avatarColor: 'bg-blue-500',
    reporter: 'Priya Sharma',
    environment: 'Production',
    createdAt: '2h ago',
    updatedAt: '1h ago',
    tags: ['NestJS', 'PostgreSQL', 'connection-pool'],
    services: ['allocation-service', 'db-primary'],
    severity: 'P0 - Outage',
    comments: [
      {
        id: 'c1',
        author: 'Rahul Kumar',
        authorInitials: 'RK',
        avatarColor: 'bg-blue-500',
        content: 'Reproduced locally. Pool size is 10 — bumping to 25 and adding queue. PR up shortly.',
        timestamp: '1h ago',
      },
    ],
  },
  {
    id: 'ENG-002',
    title: 'GCP Pub/Sub messages not being acknowledged',
    description: 'Messages in allocation-events topic are consumed but not acknowledged, causing redelivery loops. Dead-letter queue filling fast. ~12K unacknowledged messages currently.',
    status: 'In Progress',
    priority: 'Critical',
    queue: 'Infra / Cloud',
    assignee: 'Ankit Joshi',
    assigneeInitials: 'AJ',
    avatarColor: 'bg-green-500',
    reporter: 'Sneha Mishra',
    environment: 'Production',
    createdAt: '4h ago',
    updatedAt: '3h ago',
    tags: ['GCP', 'Pub/Sub', 'NestJS'],
    services: ['event-processor', 'allocation-events-topic'],
    severity: 'P0 - Outage',
    comments: [
      {
        id: 'c2',
        author: 'Ankit Joshi',
        authorInitials: 'AJ',
        avatarColor: 'bg-green-500',
        content: 'Found the issue — ack deadline is 10s but processing takes 15s. Extending deadline to 60s.',
        timestamp: '3h ago',
      },
    ],
  },
  {
    id: 'ENG-003',
    title: 'React fund dashboard showing stale data after reallocation',
    description: 'After a reallocation event, the dashboard shows old portfolio weights for 5–10 minutes. Suspected SWR cache not invalidated on mutation. Affects all v2 dashboard users.',
    status: 'Open',
    priority: 'High',
    queue: 'Frontend',
    assignee: 'Priya Sharma',
    assigneeInitials: 'PS',
    avatarColor: 'bg-purple-500',
    reporter: 'Vivek Rao',
    environment: 'Production',
    createdAt: '6h ago',
    updatedAt: '6h ago',
    tags: ['Next.js', 'React', 'SWR', 'cache'],
    services: ['dashboard-app', 'allocation-api'],
    severity: 'P1 - Degraded',
    comments: [],
  },
  {
    id: 'ENG-004',
    title: 'AWS S3 presigned URL expiry too short for large uploads',
    description: 'Investors uploading KYC documents >50MB get "URL expired" errors. Current expiry is 5 minutes. Fix: extend to 30 min + multipart upload for files >10MB.',
    status: 'In Review',
    priority: 'Medium',
    queue: 'Backend / API',
    assignee: 'Sneha Mishra',
    assigneeInitials: 'SM',
    avatarColor: 'bg-orange-500',
    reporter: 'Arjun Mehta',
    environment: 'Staging',
    createdAt: '1d ago',
    updatedAt: '2h ago',
    tags: ['AWS', 'S3', 'NestJS', 'file-upload'],
    services: ['kyc-service', 's3-documents'],
    severity: 'P2 - Minor',
    comments: [
      {
        id: 'c3',
        author: 'Sneha Mishra',
        authorInitials: 'SM',
        avatarColor: 'bg-orange-500',
        content: 'PR #442 ready. Added multipart upload and bumped expiry to 30 min.',
        timestamp: '5h ago',
      },
      {
        id: 'c4',
        author: 'Arjun Mehta',
        authorInitials: 'AM',
        avatarColor: 'bg-teal-500',
        content: 'Reviewed, 2 minor comments on chunking logic.',
        timestamp: '2h ago',
      },
    ],
  },
  {
    id: 'ENG-005',
    title: 'Node.js memory leak in portfolio calculation service',
    description: 'portfolio-calc-service RSS memory grows from 200MB to 2.1GB over 8 hours before OOMKilled. Heap snapshots show retained EventEmitter listeners in PortfolioCalculator class. Missing removeListener calls.',
    status: 'In Progress',
    priority: 'High',
    queue: 'Backend / API',
    assignee: 'Vivek Rao',
    assigneeInitials: 'VR',
    avatarColor: 'bg-red-500',
    reporter: 'Rahul Kumar',
    environment: 'Production',
    createdAt: '1d ago',
    updatedAt: '4h ago',
    tags: ['Node.js', 'memory-leak', 'EventEmitter'],
    services: ['portfolio-calc-service'],
    severity: 'P1 - Degraded',
    comments: [
      {
        id: 'c5',
        author: 'Vivek Rao',
        authorInitials: 'VR',
        avatarColor: 'bg-red-500',
        content: '40K retained listeners confirmed. Fixing in PortfolioCalculator.destroy().',
        timestamp: '12h ago',
      },
      {
        id: 'c6',
        author: 'Rahul Kumar',
        authorInitials: 'RK',
        avatarColor: 'bg-blue-500',
        content: 'Can we add a weekly heap-snapshot alert in Datadog meanwhile?',
        timestamp: '4h ago',
      },
    ],
  },
  {
    id: 'ENG-006',
    title: 'Next.js build failing on Vercel after dependency upgrade',
    description: 'npm run build fails on Vercel CI after upgrading Next.js 13.4 → 14.2. Error: "Module not found: Can\'t resolve \'@/components/charts\'". Paths correct in tsconfig but alias resolution differs in v14.',
    status: 'Open',
    priority: 'Medium',
    queue: 'Frontend',
    assignee: null,
    assigneeInitials: null,
    avatarColor: null,
    reporter: 'Ankit Joshi',
    environment: 'Staging',
    createdAt: '2d ago',
    updatedAt: '2d ago',
    tags: ['Next.js', 'Vercel', 'TypeScript', 'build'],
    services: ['investor-portal'],
    severity: 'P2 - Minor',
    comments: [],
  },
  {
    id: 'ENG-007',
    title: 'PostgreSQL slow query on allocation history table',
    description: 'SELECT on allocation_history with date range filter taking 8–12 seconds. Table has 40M rows. Missing composite index on (fund_id, created_at). EXPLAIN shows Seq Scan.',
    status: 'Resolved',
    priority: 'Medium',
    queue: 'Data / DB',
    assignee: 'Rahul Kumar',
    assigneeInitials: 'RK',
    avatarColor: 'bg-blue-500',
    reporter: 'Priya Sharma',
    environment: 'Production',
    createdAt: '3d ago',
    updatedAt: '2d ago',
    tags: ['PostgreSQL', 'performance', 'indexing'],
    services: ['db-primary', 'allocation-service'],
    severity: 'P2 - Minor',
    comments: [
      {
        id: 'c7',
        author: 'Rahul Kumar',
        authorInitials: 'RK',
        avatarColor: 'bg-blue-500',
        content: 'Added index CONCURRENTLY on (fund_id, created_at). Query now <120ms.',
        timestamp: '2d ago',
      },
    ],
  },
  {
    id: 'ENG-008',
    title: 'AWS Lambda cold start latency spike in us-east-1',
    description: 'Lambda cold starts in us-east-1 spiked to 4.5s (from 800ms baseline) after adding the new compliance-check layer (85MB). Consider provisioned concurrency or layer optimization.',
    status: 'Open',
    priority: 'Low',
    queue: 'Infra / Cloud',
    assignee: 'Ankit Joshi',
    assigneeInitials: 'AJ',
    avatarColor: 'bg-green-500',
    reporter: 'Vivek Rao',
    environment: 'Production',
    createdAt: '3d ago',
    updatedAt: '3d ago',
    tags: ['AWS', 'Lambda', 'cold-start', 'performance'],
    services: ['compliance-lambda'],
    severity: 'P3 - Cosmetic',
    comments: [],
  },
  {
    id: 'ENG-009',
    title: 'Auth token not refreshing silently in mobile PWA',
    description: 'Mobile PWA users are logged out after token expiry. Silent refresh in useAuth hook not firing when app returns from background. Issue specific to iOS Safari due to timer throttling.',
    status: 'Open',
    priority: 'High',
    queue: 'Frontend',
    assignee: 'Priya Sharma',
    assigneeInitials: 'PS',
    avatarColor: 'bg-purple-500',
    reporter: 'Sneha Mishra',
    environment: 'Production',
    createdAt: '4d ago',
    updatedAt: '4d ago',
    tags: ['Next.js', 'PWA', 'auth', 'iOS'],
    services: ['auth-service', 'investor-portal'],
    severity: 'P1 - Degraded',
    comments: [],
  },
  {
    id: 'ENG-010',
    title: 'GCP Cloud SQL failover causing 90s downtime',
    description: 'Planned Cloud SQL failover test caused 90 seconds of connection errors. Pool had no retry logic. Fix: exponential backoff reconnection added to TypeORM datasource config.',
    status: 'Resolved',
    priority: 'High',
    queue: 'Infra / Cloud',
    assignee: 'Sneha Mishra',
    assigneeInitials: 'SM',
    avatarColor: 'bg-orange-500',
    reporter: 'Ankit Joshi',
    environment: 'Production',
    createdAt: '5d ago',
    updatedAt: '4d ago',
    tags: ['GCP', 'Cloud SQL', 'TypeORM', 'failover'],
    services: ['db-replica', 'allocation-service'],
    severity: 'P1 - Degraded',
    comments: [
      {
        id: 'c8',
        author: 'Sneha Mishra',
        authorInitials: 'SM',
        avatarColor: 'bg-orange-500',
        content: 'Retry logic deployed. Tested failover again — recovery in <5s.',
        timestamp: '4d ago',
      },
    ],
  },
  {
    id: 'ENG-011',
    title: 'Kafka consumer lag growing on investor-events topic',
    description: 'Consumer group investor-event-processor has lag of 120K messages. Processing rate dropped 5K/s → 800/s after schema registry update. Deserialization errors likely due to breaking schema change.',
    status: 'In Progress',
    priority: 'High',
    queue: 'Data / DB',
    assignee: 'Vivek Rao',
    assigneeInitials: 'VR',
    avatarColor: 'bg-red-500',
    reporter: 'Rahul Kumar',
    environment: 'Production',
    createdAt: '5d ago',
    updatedAt: '3d ago',
    tags: ['Kafka', 'consumer-lag', 'schema-registry'],
    services: ['investor-event-processor', 'kafka-cluster'],
    severity: 'P1 - Degraded',
    comments: [
      {
        id: 'c9',
        author: 'Vivek Rao',
        authorInitials: 'VR',
        avatarColor: 'bg-red-500',
        content: 'Schema migration introduced a breaking change — nullable field became required. Fixing consumer to handle both versions.',
        timestamp: '3d ago',
      },
    ],
  },
  {
    id: 'ENG-012',
    title: 'Rate limiter not applying per-user limits correctly',
    description: 'NestJS ThrottlerGuard applies global limits instead of per-user limits. All users share the 100 req/min bucket. Need to override getTracker() to use userId from JWT instead of IP address.',
    status: 'Open',
    priority: 'Medium',
    queue: 'Backend / API',
    assignee: null,
    assigneeInitials: null,
    avatarColor: null,
    reporter: 'Priya Sharma',
    environment: 'Staging',
    createdAt: '6d ago',
    updatedAt: '6d ago',
    tags: ['NestJS', 'rate-limiting', 'security'],
    services: ['api-gateway'],
    severity: 'P2 - Minor',
    comments: [],
  },
]
